### ISSUE TITLE
Add a column to preview colors in the table

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/branding#1]
Here:

https://github.com/sablier-labs/branding/tree/534940fb7cf2b92377bdbf82aa48ff3f5539af6b#colors

**Comment by razgraf** [comment]
Unfortunately Github [only supports](https://github.com/BoostIO/BoostNote-Legacy/issues/905) native HEX color previews in `comments` not in `.md` files 🤯

We could use a "workaround" such as  [readme-swatches](https://github.com/luciancooper/readme-swatches) but if that service goes down, so will our color previews.

**Comment by PaulRBerg** [comment]
> if that service goes down, so will our color previews

Better than nothing, I guess (though not a priority now).
